### ISSUE TITLE
Error connection:   net::ERR_INVALID_HTTP_RESPONSE

### ISSUE THREAD

**Issue by xuanlongvts** [connectrpc/connect-es#1081]
- I have a backend server grpc serve with port: 50051
- When using connect-es config 

`const clientUser = createPromiseClient(
      UserService,
      createConnectTransport({
	      baseUrl: 'http://127.0.0.1:50051',
      })
);`

It has an error:  net::ERR_INVALID_HTTP_RESPONSE

The same status with https://github.com/grpc/grpc-web/issues/622

- I run your demo with config
`const transport = createConnectTransport({
  baseUrl: "https://demo.connectrpc.com",
});`  ---> It's ok

**Comment by srikrsna-buf** [comment]
Hey! If you are serving gRPC from the backend then you need to use `createGrpcTransport` from `@connectrpc/connect-node` package. If you are running the client on the browser, then the backend needs to support gRPC-Web or Connect. gRPC protocol doesn't work in the browser (due to browser api limitations).

**Comment by xuanlongvts** [comment]
oh. I use backend grpc with Golang language. Not use  **connect-go** . I think, i should use the same connect-go at Backend and connect-es at FE. 

Thank so much.
