### ISSUE TITLE
Incorrect Error Code Mapping for HTTP Status Code 429

### ISSUE THREAD

**Issue by EringiV3** [connectrpc/connect-es#1226]
**Is your feature request related to a problem? Please describe.**
It seems that the error code mapping for HTTP status code 429 is incorrect.
Why is it returning Unavailable instead of ResourceExhausted?

**Describe the solution you'd like**
I would like you to fix the mapping process in the codeFromHttpsStatus function.
When the HTTP status code is 429, it should return Code.ResourceExhausted.
Specifically, the following two files:
- https://github.com/connectrpc/connect-es/blob/main/packages/connect/src/protocol-grpc/http-status.ts#L33
- https://github.com/connectrpc/connect-es/blob/main/packages/connect/src/protocol-connect/http-status.ts#L34

**Comment by timostamm** [comment]
Hey @EringiV3 👋

We agree that mapping the HTTP status code 429 to the RPC error code "unavailable" is not ideal. 

If you take a look at the JSDoc for the function in [protocol-grpc/http-status.ts](https://github.com/connectrpc/connect-es/blob/v1.5.0/packages/connect/src/protocol-grpc/http-status.ts#L18-L23), you'll see that it links to a document that specifies the mapping for gRPC clients. We have to use this mapping for compatibility with other gRPC (-Web) clients.

And because the Connect protocol is designed for interoperability with gRPC, we can't change the mapping for Connect clients either. You can find more details in the [specification for the protocol](https://connectrpc.com/docs/protocol/#http-to-error-code).
