### ISSUE TITLE
Next.js calling an outside Connect server loses parameters

### ISSUE THREAD

**Issue by UntakerAnonPLAY** [connectrpc/connect-es#1294]
**Describe the bug**

When I'm trying to call an rpc method in next js environment, server doesn't see any parameters passed(default values). Calls without parameters are working. Receiving the  answer is working also. I see that parameters are actually sent via interceptors, but are just ignored by a server (I'm controlling the server also). When I call the method without next js it works. 

**Environment (please complete the following information):**

- @connectrpc/connect-node version: 1.6.1 and 2.0.0 rc2
- Next js 15.0.2
- Bun 1.34
- Node 22.9

**Comment by timostamm** [comment]
We'll need more information to reproduce. What do you mean by "parameters"? URL query parameters?

**Comment by UntakerAnonPLAY** [comment]
By parameters I mean request messages, I don't even know what info to give you to reproduce, cause I tried different versions of connect rpc and It was the same. Only strange thing I've noticed that might help you is that in 1.6.1 Interceptor on a server side of next js wasn't showing full class data of a message, but only it's data members (no functions like toBinary). Maybe because of this connect couldn't construct the network call correctly. So I switched to 2.0.0 rc2, but same behaviour.

**Comment by UntakerAnonPLAY** [comment]
*I'm making network calls using client in asynchronous page component

**Comment by UntakerAnonPLAY** [comment]
Probably a stupid question, but do I need a next js adapter if I'm using it as a server side client?

**Comment by UntakerAnonPLAY** [comment]
Cause I'm seeing an example is using it, but I thought It's only needed for server + client cases, for web client to make requests to next js. In my case I only need a client on a next js server part that calls another server.

**Comment by UntakerAnonPLAY** [comment]
Ok, so far I figured out this things:
1) Next js client to next js server is working using next js connect adapter
2) If I'm doing a request from a node connect client to a node connect server it is working
3) If I'm doing step 2 in a running next js server it is not (I have a behaviour described in the first message)
4) Also If I'm trying to do step 3 (make a request out of next js server to external connect server) without binary format, I'm getting this error:  "cannot decode message editor_api.v1.LoadRequest from JSON: JSON Parse error: Unexpected EOF"

**Comment by UntakerAnonPLAY** [comment]
Ok, for now it seems to me that connect transport from connect-node for connect client is not willing to work with next js server side. Because connect transport from gpc web is working with next js, I'm switching to it for now.

**Comment by UntakerAnonPLAY** [comment]
So If you want to reproduce - grab a connect transport from a connect node and create a client in next js server side, then try to pass any messages with payloads to a connect server. Check if payload is there. Maybe it's not where the problem lays but that's all I figured out soon. (None of the examples for next js are actually  testing this)

**Comment by UntakerAnonPLAY** [comment]
Btw, I think connect web transport is working cause next js has a global fetch, but this also introduces me to this problem "Failed to generate cache key for _Method Path_". And next js is doing some strange things with a default node http mechanism intercepting connect request

**Comment by timostamm** [comment]
There actually are two pages in the Next.js example that call another Connect server:
- [SSR using getServerSideProps](https://github.com/connectrpc/examples-es/blob/main/nextjs/pages/ssr.tsx#L22)
- [Server-side action](https://github.com/connectrpc/examples-es/blob/main/nextjs/app/react-server-actions/page.tsx#L22)

Both are calling an RPC on demo.connectrpc.com, where we run the [demo service ELIZA](https://github.com/connectrpc/examples-go). Both clients use the Connect transport from `@connecrpc/connect-web`, but they work just as well with the Connect transport from `@connectrpc/connect-node`. 

> cannot decode message editor_api.v1.LoadRequest from JSON: JSON Parse error: Unexpected EOF

This looks like an error message from the server, which didn't receive the full request. 

Unfortunately, we will not be able to help, since the two transports use different code paths, Next.js behavior varies between different contexts (getServerSideProps, RSC), and there are several other variables. This means there is a _very_ large number of different scenarios, and only a very specific one might yield the error you are seeing. 

The only way we can help you is if you provide a reproducible example.

**Comment by UntakerAnonPLAY** [comment]
Ok, fuck, it's bun, I double tested everything, and when I'm using bun I get this problem. I reproduced it using next js react server action example and fastify server example. I don't know if you care about bun support or something, but if you change tsx to bun, you can reproduce it.
