### ISSUE TITLE
Allow easier access to common fetch params

### ISSUE THREAD

**Issue by paul-sachs** [connectrpc/connect-es#64]
Some common options on the fetch function (like `credentials`) must currently be added via interceptors. While that works, we should probably expose some of these common options in a more ergonomic means:

Current:

```ts
const transport = createConnectTransport({
  baseUrl: host,
  interceptors: [
    (_service, _method, _options, request, response) => {
      return [
        {
          ...request,
          init: {
            ...request.init,
            credentials: "include",
          },
        },
        response,
      ];
    },
  ],
});
```

Proposal:

```ts
const transport = createConnectTransport({
  baseUrl: host,
  credentials: "include",
});
```

**Comment by SeanIFitch** [comment]
It seems this feature was removed with v2. Just wondering if that was an intentional change?

**Comment by timostamm** [comment]
Instead of providing `credentials` to the transport, you can override fetch.

```diff
createConnectTransport({
  baseUrl: "/",
- credentials: "include",
+ fetch: (input, init) => fetch(input, { ...init, credentials: "include" }),
});
```

See [MIGRATING.md](https://github.com/connectrpc/connect-es/blob/main/MIGRATING.md#transport-option-credentials-is-removed).

The `fetch` option supports use cases like server side rendering (where the framework often provides `fetch`), and still gives you an easy way to configure things like the `credentials` option. It was an intentional change to drop `credentials` in favor of `fetch`.
