### ISSUE TITLE
Incorrect Import Path Extensions in Generated TS Files

### ISSUE THREAD

**Issue by sugar-cat7** [connectrpc/connect-es#879]
**Description:**
The generated files, when used in a CommonJS environment, have incorrect import path extensions (`.js`). This is causing module resolution failures.

**Steps to Reproduce:**
1. Prepare the `proto` and utilize `buf` to generate the code using the following config:
```yaml
version: v1
plugins:
  - plugin: es
    out: gen
    opt: target=ts
  - plugin: connect-es
    out: gen
    opt: target=ts
```
2. Set up a CommonJS environment.
3. Use the specified libraries to generate the required files.
4. Observe the incorrect import path extensions in the generated files.

**Expected Behavior:** 
Generated files should have the correct import path extensions suitable for a CommonJS environment.

**Screenshots:**

<img width="295" alt="image" src="https://github.com/connectrpc/connect-es/assets/69241625/69c10b1a-6084-47c1-aaa5-494647274fd8">
<img width="642" alt="image" src="https://github.com/connectrpc/connect-es/assets/69241625/062d92cc-f2b4-4c1f-9c73-8d5b06cd31a4">
<img width="642" alt="image" src="https://github.com/connectrpc/connect-es/assets/69241625/90d1691c-d9cd-4171-853d-c6dbf6b438b2">

**Environment:**
- **Library/Framework Versions:**
  - `@connectrpc/connect-web`: 1.1.2
  - `@bufbuild/protobuf`: 1.3.3
  - Frontend framework: `next@13.5.4`
- **Node.js Version:** 20.8.0

**Additional Context:**
Upon reviewing the sample code provided in the [connectrpc's GitHub repository](https://github.com/connectrpc/connect-es/blob/main/packages/example/src/gen/eliza_connect.ts), I noticed that the same issue with incorrect import path extensions is also present there.

**Comment by sugar-cat7** [comment]
I may have overlooked it, but this matter might have already been discussed. If it's redundant, please ignore.
https://github.com/bufbuild/protobuf-es/issues/587

**Comment by remicaumette** [comment]
@sugar-cat7, I have the same issue, and I fixed it by setting the `import_extension` option.
```yaml
  - plugin: connect-es
    out: src
    opt: target=ts,import_extension=none
```

**Comment by timostamm** [comment]
@sugar-cat7, you can use [resolve.extensionAlias](https://webpack.js.org/configuration/resolve/#resolveextensionalias) in webpack, or the plugin option `import_extension=none`. 

We have an example [here](https://github.com/connectrpc/examples-es/blob/43c91e047202b491a4dd066a48384204edb63a87/nextjs/next.config.js#L5-L15), and documentation [here](https://connectrpc.com/docs/web/supported-browsers-and-frameworks#webpack).

It's unfortunate that webpack does not support .js extensions in TypeScript code out of the box. If you compile the code with the TypeScript compiler and run it with Node.js, you'll find that it actually compiles and runs without issues. 

Which parts of the documentation did you use to get started? Hopefully we can improve it.

**Comment by sugar-cat7** [comment]
Thank you for providing the solution! I was able to resolve the issue by following your suggested methods. :)

I stumbled upon this issue while following the documentation provided here: [Local Code Generation](https://connectrpc.com/docs/web/generating-code#local-generation).

**Comment by timostamm** [comment]
We have added this paragraph to the page:

> If your bundler does not handle the .js extension in the import from "./eliza_pb.js" correctly, you can configure it following our examples [here](https://connectrpc.com/docs/web/supported-browsers-and-frameworks#webpack), or you can add the plugin option import_extension=none to remove the extension.

Thanks for helping to improve the docs!

**Comment by alexandros-megas** [comment]
I just ran into this issue, and managed to resolve it by changing my `buf.gen.yaml` to the following:

```yaml
version: v1
plugins:
  # This will invoke protoc-gen-es
  - plugin: es
    out: clarifai-connect-grpc/gen
    opt:
      - target=ts
      - import_extension=none
  # This will invoke protoc-gen-connect-es
  - plugin: connect-es
    out: clarifai-connect-grpc/gen
    opt:
      - target=ts
      - import_extension=none
```

> It's unfortunate that webpack does not support .js extensions in TypeScript code out of the box. If you compile the code with the TypeScript compiler and run it with Node.js, you'll find that it actually compiles and runs without issues.

Why would it be the bundler's job to change which file extension it matches? As I understand it, most bundler will let you leave off the extension, in which case it will go through a list of various extensions like js, ts, jsx, tsx, mjs, etc, in which case, the generated module `greet_pb.ts` would have been found eventually, and it would have worked. The problem was that the code that was generated was all `.ts` files, but the generated code had imports to `greet_pb.js` so if you specify the extension, most bundlers won't try to second guess what you wanted, and instead try to give you exactly what you requested.

In my opinion, `import_extension` should be set to `none` by default, since if I'm not mistaken, all bundlers and even node will support this behavior, and even newer runtimes like Deno which try to create stricter behavior will often include compatibility for node conventions (though I haven't tested any of this). Shy of this, I think the `buf.gen.yaml` file on that page should include it because then it will actually work regardless of the extension.

In my next.js (which uses webpack), when I use the sample `buf.gen.yaml` with just `target=ts`, here's the directory and code that I see:

<img width="1477" alt="image" src="https://github.com/connectrpc/connect-es/assets/55400979/3cc20c99-c44f-415d-b948-f677bd788f2d">

Trying to build this app fails, because it's looking for a non-existent `.js` file. When I add the `import_extension=none` option and regenerate the code, I get the following output:

<img width="1361" alt="image" src="https://github.com/connectrpc/connect-es/assets/55400979/18cffffd-d81b-4ddd-80f8-60b53c00c5f4">

This version builds correctly in my next.js app, and I imagine most bundlers out there also include this "fallback" of selecting from a variety of extensions if no extension is specified.

Apologies if I'm misunderstanding the issue, but to me it seems pretty clear that the code generator is incorrectly adding a `.js` extension when it's outputting `ts` code, because I don't have any `.js` files anyway, how could that ever work (other than re-mapping the `js` extension back to `ts` as your workaround section suggests).

**Comment by timostamm** [comment]
> even node will support this behavior

Unfortunately, that is not the case, @alexandros-megas. From the [TypeScript handbook](https://www.typescriptlang.org/docs/handbook/modules/theory.html#module-resolution-is-host-defined):

> In Node.js, module specifiers in import statements and dynamic import() calls are not allowed to omit file extensions or /index.js suffixes

Node.js is following the ECMAScript spec, TypeScript and browsers too, but bundlers have not caught up. [Here's an issue](https://github.com/vercel/next.js/issues/59744) filed against next.js. Webpack added the option `extensionAlias` to mitigate.

When we initially wrote the code generator about two years ago, we expected bundlers to update much more quickly. Unfortunately, they haven't yet. We'll consider to change the default behavior to generate no import extension in the next major version, if the situation has not improved.
